#!/bin/bash
# An action named "rumble"
# It just runs pyapp.run (that prints two messages to syslog and a Rumble to stdout)

o=$(/snap/bin/pyapp.run)

action-set result-map.time-completed="$(date)" result-map.message="$o"

action-set outcome="success"
